- hosts: tag_ansible_fedora
  user: ubuntu
  become: yes
  become_user: root
  tasks:

    - name: Transfer Fedora Bootstrap script
      copy: src=../user_scripts/ubuntu_fedora_bootstrap.sh dest=/ mode=0777

    - name: Run Fedora Bootstrap to install Fedora
      command: ./ubuntu_fedora_bootstrap.sh
      args:
        chdir: /